### ISSUE TITLE
Output charts

### ISSUE THREAD

**Issue by bitedgeco** [bitaverage/bitaverage#29]
using either

http://www.chartjs.org/

or

http://lavacharts.com/

**Comment by dcurran89** [comment]
Have all charts outputting, need to get selection of get average working, need to change charts from cents to dollars, fix horizontal axis to have less data points. For monthly charts have them load separately.

**Comment by bitedgeco** [comment]
It would be cool if he had a horizontal line along the value of the averages. I do think the charts on 

http://bitaverage.dev/monthly-and-yearly-averages

should only plot the monthly average figure, this would make them 30 times smaller and probably not need to load separately.

**Comment by bitedgeco** [comment]
I have broken what is left of this into separate issues.
